services:
  backend:
    image: ghcr.io/chaykov/chaykov-backend:latest
    container_name: chaykov-saas-backend
    ports:
      - "3000:3000"

  frontend:
    image: ghcr.io/chaykov/chaykov-frontend:latest
    container_name: chaykov-saas-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
