name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/chaykov-saas-app
            git pull origin main
            sudo /var/www/chaykov-saas-app/deploy.sh production

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "Frontend: https://polytalko.com"
          echo "API: https://polytalko.com/api"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Deployment failed! Check logs."
          exit 1
