name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          REMOTE_PORT: ${{ secrets.VPS_PORT }}
          SCRIPT_BEFORE: |
            cd /var/www/chaykov-saas-app
            git pull origin main
          SCRIPT_AFTER: |
            sudo /var/www/chaykov-saas-app/deploy.sh production

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "Frontend: https://polytalko.com"
          echo "API: https://polytalko.com/api"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Deployment failed! Check logs."
          exit 1
