name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - Check secrets are set
        run: |
          echo "VPS_HOST is set: ${{ secrets.VPS_HOST != '' }}"
          echo "VPS_USER is set: ${{ secrets.VPS_USER != '' }}"
          echo "VPS_PORT is set: ${{ secrets.VPS_PORT != '' }}"
          echo "VPS_SSH_KEY is set: ${{ secrets.VPS_SSH_KEY != '' }}"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS via SSH
        run: |
          ssh -i ~/.ssh/deploy_key -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /var/www/chaykov-saas-app
            git pull origin main
            sudo /var/www/chaykov-saas-app/deploy.sh production
          EOF

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "Frontend: https://polytalko.com"
          echo "API: https://polytalko.com/api"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Deployment failed! Check logs."
          exit 1
